import type { Difficulty, JobType, Question } from "./types";

export const QUESTIONS: Question[] = [
  // Beginner — general
  {
    id: "q-tell-me-about-yourself",
    text: "Tell me about yourself.",
    category: "general",
    difficulty: "beginner",
    jobTypes: ["general", "technology", "business", "customer_service", "creative"],
    starRelevant: false,
  },
  {
    id: "q-why-this-role",
    text: "Why are you interested in this position?",
    category: "general",
    difficulty: "beginner",
    jobTypes: ["general", "technology", "business", "customer_service", "creative"],
    starRelevant: false,
  },
  {
    id: "q-strengths",
    text: "What would you say is your greatest strength?",
    category: "general",
    difficulty: "beginner",
    jobTypes: ["general", "technology", "business", "customer_service", "creative"],
    starRelevant: false,
  },
  {
    id: "q-weakness",
    text: "What is something you're working to improve about yourself?",
    category: "general",
    difficulty: "beginner",
    jobTypes: ["general", "technology", "business", "customer_service", "creative"],
    starRelevant: false,
  },
  {
    id: "q-why-you",
    text: "Why should we choose you over other candidates?",
    category: "general",
    difficulty: "beginner",
    jobTypes: ["general", "technology", "business", "customer_service", "creative"],
    starRelevant: false,
  },
  {
    id: "q-work-style",
    text: "How would a previous teacher, coach, or supervisor describe your work style?",
    category: "general",
    difficulty: "beginner",
    jobTypes: ["general", "technology", "business", "customer_service", "creative"],
    starRelevant: false,
  },
  {
    id: "q-tech-why",
    text: "What got you interested in technology or programming?",
    category: "general",
    difficulty: "beginner",
    jobTypes: ["technology"],
    starRelevant: false,
  },
  {
    id: "q-business-why",
    text: "What interests you about working in a business environment?",
    category: "general",
    difficulty: "beginner",
    jobTypes: ["business"],
    starRelevant: false,
  },
  {
    id: "q-cs-why",
    text: "What do you think makes someone great at helping customers?",
    category: "general",
    difficulty: "beginner",
    jobTypes: ["customer_service"],
    starRelevant: false,
  },
  {
    id: "q-creative-why",
    text: "What draws you to creative work?",
    category: "general",
    difficulty: "beginner",
    jobTypes: ["creative"],
    starRelevant: false,
  },

  // Intermediate — behavioral (STAR-relevant)
  {
    id: "q-difficult-problem",
    text: "Tell me about a time you solved a difficult problem.",
    category: "behavioral",
    difficulty: "intermediate",
    jobTypes: ["general", "technology", "business", "customer_service", "creative"],
    starRelevant: true,
    followUp: "What would you do differently if you faced that same problem again today?",
  },
  {
    id: "q-teamwork",
    text: "Describe a time you worked as part of a team to accomplish a goal.",
    category: "behavioral",
    difficulty: "intermediate",
    jobTypes: ["general", "technology", "business", "customer_service", "creative"],
    starRelevant: true,
    followUp: "How did you handle a teammate who wasn't contributing equally?",
  },
  {
    id: "q-missed-deadline",
    text: "Tell me about a time you had to manage multiple priorities or a tight deadline.",
    category: "behavioral",
    difficulty: "intermediate",
    jobTypes: ["general", "business", "technology"],
    starRelevant: true,
  },
  {
    id: "q-mistake",
    text: "Describe a mistake you made at work or school and how you handled it.",
    category: "behavioral",
    difficulty: "intermediate",
    jobTypes: ["general", "technology", "business", "customer_service", "creative"],
    starRelevant: true,
  },
  {
    id: "q-customer-issue",
    text: "Tell me about a time you had to deal with a frustrated or upset customer.",
    category: "behavioral",
    difficulty: "intermediate",
    jobTypes: ["customer_service", "business"],
    starRelevant: true,
  },
  {
    id: "q-creative-constraint",
    text: "Describe a project where you had to be creative within a strict limitation, like budget or time.",
    category: "behavioral",
    difficulty: "intermediate",
    jobTypes: ["creative"],
    starRelevant: true,
  },
  {
    id: "q-debug-story",
    text: "Tell me about a time you had to track down and fix a difficult bug or technical issue.",
    category: "behavioral",
    difficulty: "intermediate",
    jobTypes: ["technology"],
    starRelevant: true,
  },
  {
    id: "q-learned-quickly",
    text: "Describe a time you had to learn a new skill or tool quickly to finish something.",
    category: "behavioral",
    difficulty: "intermediate",
    jobTypes: ["general", "technology", "business", "customer_service", "creative"],
    starRelevant: true,
  },
  {
    id: "q-initiative",
    text: "Tell me about a time you noticed a problem that wasn't officially your responsibility and took action anyway.",
    category: "behavioral",
    difficulty: "intermediate",
    jobTypes: ["general", "technology", "business", "customer_service", "creative"],
    starRelevant: true,
  },
  {
    id: "q-feedback-received",
    text: "Describe a time you received critical feedback on your work. How did you respond?",
    category: "behavioral",
    difficulty: "intermediate",
    jobTypes: ["general", "technology", "business", "customer_service", "creative"],
    starRelevant: true,
  },
  {
    id: "q-going-above",
    text: "Tell me about a time you went above and beyond for a customer or client.",
    category: "behavioral",
    difficulty: "intermediate",
    jobTypes: ["customer_service", "business"],
    starRelevant: true,
  },
  {
    id: "q-policy-conflict",
    text: "Describe a situation where a customer wanted something that went against policy. How did you handle it?",
    category: "behavioral",
    difficulty: "intermediate",
    jobTypes: ["customer_service"],
    starRelevant: true,
  },
  {
    id: "q-scope-change",
    text: "Tell me about a time project requirements or expectations changed midway through. How did you adapt?",
    category: "behavioral",
    difficulty: "intermediate",
    jobTypes: ["technology", "business"],
    starRelevant: true,
  },
  {
    id: "q-creative-feedback",
    text: "Describe a time someone didn't like your creative work. How did you handle the feedback?",
    category: "behavioral",
    difficulty: "intermediate",
    jobTypes: ["creative"],
    starRelevant: true,
  },
  {
    id: "q-process-improve",
    text: "Tell me about a time you improved a process or made something more efficient.",
    category: "behavioral",
    difficulty: "intermediate",
    jobTypes: ["general", "technology", "business"],
    starRelevant: true,
  },
  {
    id: "q-explain-technical",
    text: "Describe a time you had to explain something technical to someone without a technical background.",
    category: "technical",
    difficulty: "intermediate",
    jobTypes: ["technology"],
    starRelevant: true,
  },

  // Advanced — behavioral with sharper follow-ups
  {
    id: "q-disagreement",
    text: "Tell me about a time you disagreed with a team member. How did you handle the situation?",
    category: "behavioral",
    difficulty: "advanced",
    jobTypes: ["general", "technology", "business", "customer_service", "creative"],
    starRelevant: true,
    followUp: "You mentioned you led that project. What was the most difficult decision you had to make as the leader?",
  },
  {
    id: "q-failure",
    text: "Tell me about a time you failed at something important. What did you learn?",
    category: "behavioral",
    difficulty: "advanced",
    jobTypes: ["general", "technology", "business", "customer_service", "creative"],
    starRelevant: true,
    followUp: "Looking back, what's one thing you wish you had done differently in the moment?",
  },
  {
    id: "q-influence-without-authority",
    text: "Describe a time you had to convince others to support an idea when you weren't formally in charge.",
    category: "behavioral",
    difficulty: "advanced",
    jobTypes: ["general", "business", "technology"],
    starRelevant: true,
  },
  {
    id: "q-ethical-dilemma",
    text: "Tell me about a time you faced an ethical dilemma or had to make a difficult judgment call.",
    category: "behavioral",
    difficulty: "advanced",
    jobTypes: ["general", "business", "technology", "customer_service"],
    starRelevant: true,
  },
  {
    id: "q-scaling-tradeoff",
    text: "Describe a situation where you had to choose between doing something quickly and doing it thoroughly.",
    category: "technical",
    difficulty: "advanced",
    jobTypes: ["technology"],
    starRelevant: true,
  },
  {
    id: "q-difficult-stakeholder",
    text: "Tell me about a time you had to manage a difficult stakeholder, client, or supervisor's expectations.",
    category: "behavioral",
    difficulty: "advanced",
    jobTypes: ["general", "business", "technology"],
    starRelevant: true,
    followUp: "What signs did you notice that the relationship was strained before it became a real problem?",
  },
  {
    id: "q-underperforming-peer",
    text: "Describe a time you had to address a peer or teammate whose work was consistently below expectations.",
    category: "behavioral",
    difficulty: "advanced",
    jobTypes: ["general", "business", "technology"],
    starRelevant: true,
  },
  {
    id: "q-limited-information",
    text: "Tell me about a time you had to make an important decision without having all the information you wanted.",
    category: "behavioral",
    difficulty: "advanced",
    jobTypes: ["general", "technology", "business"],
    starRelevant: true,
    followUp: "What would have changed about your decision if you'd had one more day to gather information?",
  },
  {
    id: "q-conflicting-priorities",
    text: "Describe a time two people you respected gave you conflicting advice or instructions. How did you decide what to do?",
    category: "behavioral",
    difficulty: "advanced",
    jobTypes: ["general", "business", "technology", "customer_service", "creative"],
    starRelevant: true,
  },
  {
    id: "q-system-design",
    text: "Walk me through how you'd approach designing a solution to a problem you've never solved before.",
    category: "technical",
    difficulty: "advanced",
    jobTypes: ["technology"],
    starRelevant: false,
  },
  {
    id: "q-de-escalate",
    text: "Tell me about the most difficult customer situation you've ever handled and how you de-escalated it.",
    category: "behavioral",
    difficulty: "advanced",
    jobTypes: ["customer_service"],
    starRelevant: true,
    followUp: "Looking back, was there an earlier point where the situation could have been prevented entirely?",
  },
  {
    id: "q-creative-rejection",
    text: "Describe a time your creative concept was rejected entirely. What did you do next?",
    category: "behavioral",
    difficulty: "advanced",
    jobTypes: ["creative"],
    starRelevant: true,
  },

  // General/technical closers
  {
    id: "q-questions-for-us",
    text: "Do you have any questions for me about the role or the company?",
    category: "general",
    difficulty: "beginner",
    jobTypes: ["general", "technology", "business", "customer_service", "creative"],
    starRelevant: false,
  },
  {
    id: "q-where-in-5-years",
    text: "Where do you see yourself in five years?",
    category: "general",
    difficulty: "beginner",
    jobTypes: ["general", "technology", "business", "customer_service", "creative"],
    starRelevant: false,
  },
  {
    id: "q-why-leave-explore",
    text: "What are you hoping to get out of this opportunity that you haven't had before?",
    category: "general",
    difficulty: "beginner",
    jobTypes: ["general", "technology", "business", "customer_service", "creative"],
    starRelevant: false,
  },
  {
    id: "q-work-environment",
    text: "What kind of work environment brings out your best work?",
    category: "general",
    difficulty: "beginner",
    jobTypes: ["general", "technology", "business", "customer_service", "creative"],
    starRelevant: false,
  },
];

export function questionsFor(jobType: JobType, difficulty: Difficulty): Question[] {
  return QUESTIONS.filter(
    (q) => q.difficulty === difficulty && (q.jobTypes.includes(jobType) || q.jobTypes.includes("general")),
  );
}

/** A question not already asked this session, preferring the requested difficulty and falling back one tier if that pool is empty. */
export function pickNextQuestion(jobType: JobType, difficulty: Difficulty, askedIds: Set<string>): Question | null {
  const tiers: Difficulty[] = difficulty === "advanced"
    ? ["advanced", "intermediate", "beginner"]
    : difficulty === "intermediate"
      ? ["intermediate", "beginner", "advanced"]
      : ["beginner", "intermediate", "advanced"];

  for (const tier of tiers) {
    const pool = questionsFor(jobType, tier).filter((q) => !askedIds.has(q.id));
    if (pool.length > 0) return pool[Math.floor(Math.random() * pool.length)];
  }
  return null;
}
